### ISSUE TITLE
Can you release the version to PyPi?

### ISSUE THREAD

**Issue by lolobosse** [hustcc/timeago#18]
Not to have to use `editable` packages?

Thx

**Comment by hustcc** [comment]
Do you have time to help maintain this project?

My work now is fed, did not write Python for long time.

if you can, I will add you into the project, include release versions.

**Comment by lolobosse** [comment]
Yep I should be able to do that 😄 

However, I need to have a look at how to release on pyPi

**Comment by hustcc** [comment]
Collaborators will do:

 - process issue and pr
 - re

**Comment by lolobosse** [comment]
lolobosse

**Comment by hustcc** [comment]
Done, add you as Maintainer on pypi and github.
