### ISSUE TITLE
Remove "in X hours ago" ??

### ISSUE THREAD

**Issue by Ovicron** [hustcc/timeago#33]
Hi, How do I remove "IN X HOURS AGO", I only want it to show "X hours/days/minutes ago" and not "in X hours ago"
It does work, but on some instances it shows "3 hours ago" and in some other instances it shows "in 3 hours"... 
Using Python..

`        

        now = datetime.datetime.now() + datetime.timedelta(seconds=60 * 3.4)

        date = datetime.datetime.now()

        time_ago = (timeago.format(streamer_channel_info['last_seen']))`

**Comment by yangze01** [comment]
I encounter the same situation. I want to get "xxx time ago", but sometimes I get "in xxx time". how can I fix it to "xxx time ago"
